# Copyright (c) 2022 Robert Bosch GmbH and Microsoft Corporation
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.imageVehicledatabroker.name}}
  labels:
    app: {{.Values.imageVehicledatabroker.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.imageVehicledatabroker.name}}
  template:
    metadata:
      labels:
        app: {{.Values.imageVehicledatabroker.name}}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{.Values.imageVehicledatabroker.name}}"
        {{- with (index .Values.imageVehicledatabroker.ports 0) }}
        dapr.io/app-port: "{{.port}}"
        {{- end }}
        dapr.io/log-level: "debug"
        dapr.io/config: "config"
        dapr.io/app-protocol: "grpc"
    spec:
      containers:
        - name: {{.Values.imageVehicledatabroker.name}}
          image: {{.Values.imageVehicledatabroker.repository}}:{{.Values.imageVehicledatabroker.tag}}
          imagePullPolicy: {{.Values.imageVehicledatabroker.pullPolicy}}
        {{- if .Values.imageVehicledatabroker.ports}}
          ports:
          {{- range $i, $port := .Values.imageVehicledatabroker.ports }}
            - name: default{{ $i }}
              containerPort: {{ .port }}
              protocol: TCP
          {{- end }}
        {{- end }}
        {{- if .Values.imageVehicledatabroker.environmentVariables}}
          env:
          {{- range .Values.imageVehicledatabroker.environmentVariables }}
            - name: {{ .name }}
              value: "{{ .value }}"
          {{- end }}
        {{- end }}
        {{- if .Values.vspecFilePath }}
        # TODO: This need to be checked and probably reworked again
          env:
            - name: KUKSA_DATA_BROKER_METADATA_FILE
              value: "{{.Values.vspecFilePath}}"
          volumeMounts:
          - name: vspec
            mountPath: "{{.Values.vspecFilePath}}"
            subPath: vspec.json
      volumes:
        - name: vspec
          configMap:
            name: vspec-config
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.imageVehicledatabroker.name}}-nodeport
spec:
  type: NodePort
  selector:
    app: {{.Values.imageVehicledatabroker.name}}
  ports:
  {{- with (index .Values.imageVehicledatabroker.ports 0) }}
    - port: {{.port}}
      targetPort: {{.port}}
      nodePort: {{.nodePort}}
  {{- end }}
